---
- name: install nginx
  yum: name=nginx

- name: remove default configuration
  file: >
    path=/etc/nginx/conf.d/default.conf
    state=absent
  notify: reload nginx

- name: add vecnet configuration
  template: >
    src={{ item }}.j2
    dest=/etc/nginx/{{ item }}
    owner=nginx
    group=nginx
  with_items:
    - conf.d/tomcat.conf
    - conf.d/vecnet.conf
    - nginx.conf
  notify: reload nginx

- name: make www dir
  file: >
    path=/opt/www
    owner=nginx
    group=nginx
    mode=554
    state=directory

- name: copy robots.txt
  template: >
    src=robots.txt.j2
    dest=/opt/www/robots.txt
    owner=nginx
    group=nginx
    mode=554

- name: start nginx
  service: >
    name=nginx
    enabled=yes
    state=started

# ensure the app can parse the logs
- name: adjust nginx logrotate
  lineinfile: >
    dest=/etc/logrotate.d/nginx
    state=absent
    regexp=create
