---
- name: download fits
  get_url: >
    url={{ fits_cache_url }}/fits-{{ fits_version }}.zip
    dest=/opt/pkg/fits-{{ fits_version }}.zip

- name: expand fits
  unarchive: >
    src=/opt/pkg/fits-{{ fits_version }}.zip
    dest=/opt/src
    copy=no
    owner=root
    group=root
    creates=/opt/src/fits-{{ fits_version }}/fits.sh
  become: yes

- name: link fits to /opt
  file: >
    src=/opt/src/fits-{{ fits_version }}
    dest=/opt/fits
    state=link
  become: yes

- name: make fits executable
  file: >
    path=/opt/fits/fits.sh
    state=file
    mode=0755
  become: yes

