---
- name: Install main
  hosts:
      - main
  become: yes
  roles:
      - common
      - tarcache
      - postgres
      - redis
      - tomcat
      - solr
      - fedora
      - nginx
      - redis
      - fits
      - noids
      - ruby
      - discovery
      - vecnet
      - disadis


- name: Install rsync backup
  hosts:
      - dataserver
  become: yes
  roles:
      - backup-client


- name: Install workers
  hosts:
      - workers
  become: yes
  vars:
      for_worker: true
  roles:
      - common
      - fits
      - ruby
      - vecnet


- name: Setup standalone
  hosts:
    - standalone
  become: yes
  roles:
      - common
      - postgres
      - tomcat
      - solr
      - fedora
      - nginx
      - redis
      - noids
      - fits
      - ruby
      - discovery
      - vecnet
      - disadis

# The geosuite role needs some adjustement
# to configure the geoserver (it needs to
# change the redirect address and port)
#- name: Install geoserver
#  hosts: geoserver
#  sudo: yes
#  roles:
#    - common
#    - geosuite
