---
# populate the local cache of external files needed
# for deploy.
#
# The intention is that this is just stored on a single local box.

- name: create www
  file: >
      path=/opt/www
      state=directory

- name: create www/i
  file: >
      path=/opt/www/i
      state=directory

- name: download files
  get_url:
      url={{ item.url }}
      dest=/opt/www/i/{{ item.dest }}
  with_items:
      - {
          dest: solr-{{ solr_version }}.tgz,
          url: http://apache.mirrors.lucidnetworks.net/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz
        }
      - {
          dest: fcrepo-installer-{{ fedora_version }}.jar,
          url: http://repo1.maven.org/maven2/org/fcrepo/fcrepo-installer/{{ fedora_version }}/fcrepo-installer-{{ fedora_version }}.jar
        }
      - {
          dest: fits-{{ fits_version }}.zip,
          url: http://projects.iq.harvard.edu/files/fits/files/fits-{{ fits_version }}.zip
        }
      - {
          dest: chruby-{{ chruby_version }}.tar.gz,
          url: https://github.com/postmodern/chruby/archive/v{{ chruby_version }}.tar.gz
        }

