---
- name: install log4j
  become: yes
  yum: >
    name=log4j
    state=present

- name: Check variable solr_version is set
  fail: msg="Please set 'solr_version' variable in the playbook"
  when: solr_version is not defined

- name: Download Solr
  get_url: >
    url={{ solr_cache_url }}/solr-{{ solr_version }}.tgz
    dest=/opt/pkg/solr-{{ solr_version }}.tgz
    owner=tomcat
    group=tomcat
  become: yes

- name: Setup directories
  file: >
    path={{ item }}
    state=directory
    owner=tomcat
    group=tomcat
  become: yes
  with_items:
    - /opt/solr
    - /opt/solr/bin
    - /opt/solr/lib

- name: Unpack SOLR
  unarchive: >
    src=/opt/pkg/solr-{{ solr_version }}.tgz
    dest=/opt/src
    creates=/opt/src/solr-{{ solr_version }}/dist/solr-{{ solr_version }}.war
    copy=no
    group=tomcat
    owner=tomcat
  become: yes

- name: Copy solr.war into place
  command: >
    cp /opt/src/solr-{{ solr_version }}/dist/solr-{{ solr_version }}.war
    /opt/solr/solr-{{ solr_version }}.war
    creates=/opt/solr/solr-{{ solr_version }}.war
  become: yes

- name: copy solr jar files
  command: >
    cp /opt/src/solr-{{ solr_version }}/{{ item }}
    /opt/solr/lib
    creates=/opt/solr/lib/{{ item | basename }}
  become: yes
  with_items:
    - dist/solr-analysis-extras-{{solr_version}}.jar
    - dist/solr-cell-{{solr_version}}.jar
    - dist/solr-clustering-{{solr_version}}.jar
    - dist/solr-core-{{solr_version}}.jar
    - dist/solr-dataimporthandler-{{solr_version}}.jar
    - dist/solr-dataimporthandler-extras-{{solr_version}}.jar
    - dist/solr-langid-{{solr_version}}.jar
    - dist/solr-map-reduce-{{solr_version}}.jar
    - dist/solr-morphlines-cell-{{solr_version}}.jar
    - dist/solr-morphlines-core-{{solr_version}}.jar
    - dist/solr-solrj-{{solr_version}}.jar
    - dist/solr-test-framework-{{solr_version}}.jar
    - dist/solr-uima-{{solr_version}}.jar
    - dist/solr-velocity-{{solr_version}}.jar
    - contrib/analysis-extras/lib/icu4j-53.1.jar
    - contrib/analysis-extras/lucene-libs/lucene-analyzers-icu-{{solr_version}}.jar

- name: copy solr logging jars
  command: >
    cp /opt/src/solr-{{ solr_version }}/example/{{ item }}
    /usr/share/tomcat6/lib
    creates=/usr/share/tomcat6/lib/{{ item | basename }}
  become: yes
  with_items:
    - lib/ext/jcl-over-slf4j-1.7.6.jar
    - lib/ext/jul-to-slf4j-1.7.6.jar
    - lib/ext/log4j-1.2.17.jar
    - lib/ext/slf4j-api-1.7.6.jar
    - lib/ext/slf4j-log4j12-1.7.6.jar
    - resources/log4j.properties

- name: configure solr lib paths
  lineinfile: >
    line="common.loader=${catalina.base}/lib,${catalina.base}/lib/*.jar,${catalina.home}/lib,${catalina.home}/lib/*.jar,/opt/solr-4.3.0/lib/ext/*.jar,/opt/solr-4.3.0/lib/contrib/extraction/lib/*.jar"
    regexp="^common.loader"
    dest=/etc/tomcat6/catalina.properties
  become: yes

- name: Correct solr files ownership
  become: yes
  file: >
    path=/opt/solr
    state=directory
    recurse=yes
    owner=tomcat
    group=tomcat

- name: Install solr configuration
  become: yes
  template: >
    src=solr.xml.j2
    dest=/opt/solr/solr.xml
    owner=tomcat
    group=tomcat

#
# setup vecnet core
#

- name: Setup vecnet directory
  file: >
    path=/opt/solr/vecnet/conf
    state=directory
    owner=tomcat
    group=tomcat
  become: yes

- name: Copy vecnet solr config
  copy: >
    src=vecnet/{{ item }}
    dest=/opt/solr/vecnet/conf/{{ item }}
    owner=tomcat
    group=tomcat
    mode=644
  become: yes
  with_items:
    - protwords.txt
    - schema.xml
    - solrconfig.xml
    - stopwords.txt
    - stopwords_en.txt
    - synonyms.txt
  notify: restart tomcat

#
# setup discovery core
#

- name: Setup discovery directory
  file: >
    path=/opt/solr/discovery/conf
    state=directory
    owner=tomcat
    group=tomcat
  become: yes

- name: Copy discovery solr config
  copy: >
    src=discovery/{{ item }}
    dest=/opt/solr/discovery/conf/{{ item }}
    owner=tomcat
    group=tomcat
    mode=644
  become: yes
  with_items:
    - protwords.txt
    - schema.xml
    - solrconfig.xml
    - stopwords_en.txt
    - synonyms.txt
  notify: restart tomcat

- name: Copy solr.xml into tomcat
  become: yes
  template: >
    src=solr-production.j2
    dest=/etc/tomcat6/Catalina/localhost/solr.xml
    owner=tomcat
    group=tomcat
  notify: restart tomcat
