---
- name: create /opt hierarchy
  file: >
      path=/opt/{{ item }}
      state=directory
      mode=0777
  with_items:
      - src
      - pkg
      - gocode
      - sv
      - log

# make /data/io ?

- include: packages.yml
  become: true

- include: ferm.yml

