---

# and alternate way to install rubies than compiling them with ruby-build

- name: download ruby-install
  get_url: >
    url=https://github.com/postmodern/ruby-install/archive/v0.5.0.tar.gz
    dest=/opt/pkg/ruby-install-0.5.0.tar.gz

- name: expand ruby-install
  unarchive: >
    src=/opt/pkg/ruby-install-0.5.0.tar.gz
    dest=/opt/src
    copy=no
    creates=/opt/src/ruby-install-0.5.0/Makefile

- name: compile ruby-install
  become: yes
  command: >
    make install
    chdir=/opt/src/ruby-install-0.5.0
    creates=/usr/local/bin/ruby-install

- name: install ruby
  command: >
    /usr/local/bin/ruby-install --rubies-dir /opt/rubies ruby {{ ruby_version }}
    creates=/opt/rubies/ruby-{{ ruby_version }}/bin/ruby

