---
# this is mostly identical to the "vecnet" role, which deploys the backend application
- name: make app user
  user: name=app

- name: install packages
  yum: >
    name={{ item }}
    state=present
  with_items:
    - postgresql-devel

- name: install bundler
  shell: >
    source /etc/profile.d/chruby.sh && chruby {{ ruby_version }} && gem install bundler
    chdir=/home/app
    creates=/home/app/.gem/ruby/2.0.0/bin/bundle
  become_user: app
  become: yes
  # TODO: does this creates path depends on the ruby version? how to strip the patch level off the ruby_version?

# capistrano-like directory layout
# But not perfect, since the capistrano way is not idempotent
#
# This way isn't perfect either since the git checkout could return
# different things each time...is this a difference between
# provisioning and deploying?

- name: setup application directory layout
  file: >
    path={{ discovery_deploy_root }}/{{ item }}
    state=directory
    owner=app
    group=app
    mode=755
  with_items:
    - releases
    - shared
    - shared/bundle
    - shared/config
    - shared/log
    - shared/pids
    - shared/indexing
    - shared/system

- name: check out code
  git: >
    repo="https://github.com/vecnet/dl-discovery.git"
    dest={{ discovery_deploy_root }}/shared/cached-copy
    force=yes
    recursive=no
    version={{ discovery_branch|d('master') }}

- name: HEAD ref
  command: git rev-parse --verify HEAD
    chdir={{ discovery_deploy_root }}/shared/cached-copy
  register: head_ref

- name: See if directory exists
  command: ls {{ discovery_deploy_root }}/releases/{{ head_ref.stdout }}
  register: deploy_exists
  ignore_errors: yes

- name: Do deployment
  include: deploy.yml
  #when: deploy_exists.rc != 0
  vars:
    release_dir: "{{ discovery_deploy_root }}/releases/{{ head_ref.stdout }}"

- name: Fix permissions
  file: >
    path={{ discovery_deploy_root }}
    state=directory
    owner=app
    group=app
    mode=755
    recurse=yes

- name: link current directory
  file: >
    src={{ discovery_deploy_root }}/releases/{{ head_ref.stdout }}
    path={{ discovery_deploy_root }}/current
    state=link

- name: restart unicorn
  command: >
      {{ discovery_deploy_root }}/current/script/reload-unicorn.sh
  become_user: app
  become: yes

- name: link assets directory
  file: >
    src={{ discovery_deploy_root }}/current/public
    path=/opt/www/assets-discovery
    state=link
    owner=nginx
    group=nginx
    mode=755

- name: install log rotate
  template: >
    src=logrotate.j2
    dest=/etc/logrotate.d/vecnet-discovery
    owner=root
    group=root
    mode=644

- name: install init.d
  template: >
      src=vecnet-discovery.j2
      dest=/etc/init.d/vecnet-discovery
      mode=655

- name: start server on startup
  command: /sbin/chkconfig vecnet-discovery on

# This runs every five minutes
- name: install DL harvest cron job
  cron: >
      name="discovery dl harvest"
      user=app
      state=present
      minute=*/5
      job="/opt/vecnet-discovery/current/script/harvest-cron-job.sh dl 1>/dev/null 2>&1"

# this runs once a day
# add the job, but comment it out since the target CI server appears to be gone
- name: install CI harvest cron job
  cron: >
      name="discovery ci harvest"
      user=app
      state=present
      disabled=yes
      hour=0
      minute=30
      job="/opt/vecnet-discovery/current/script/harvest-cron-job.sh ci"

