---
#
# Variables used here
#   vecnet_deploy_root - path to where to put code
#   release_dir - the directory for the new release
#

- name: copy code to directory
  command: cp -RPp {{ vecnet_deploy_root }}/shared/cached-copy {{ release_dir }}

- name: fix permissions on release_dir
  file: >
    path={{ release_dir }}
    state=directory
    owner=app
    group=app
    mode=755
    recurse=yes

- name: ensure release_dir/tmp exists
  file: >
    path={{ release_dir }}/tmp
    state=directory
    owner=app
    group=app
    mode=755

- name: link in the shared directories
  file: >
    src={{ vecnet_deploy_root }}/shared/{{ item.src }}
    path={{ release_dir }}/{{ item.target }}
    state=link
  with_items:
      - { src: system,  target: public/system }
      - { src: log,     target: log }
      - { src: pids,    target: tmp/pids }
      - { src: var,     target: tmp/var }

- name: Install config files
  template: >
    src={{ item }}.j2
    dest={{ release_dir }}/config/{{ item }}
  with_items:
      - database.yml
      - fedora.yml
      - redis.yml
      - initializers/secret_token.rb
      - solr.yml

- name: Point application to pubtkt key
  lineinfile: >
      dest={{ release_dir }}/config/environments/{{ item }}
      regexp='pubtkt_key_file\s*='
      line="pubtkt_key_file = \"{{ pubtkt_public_key_path }}\""
      state=present
  with_items:
      - production.rb
      - qa.rb

- name: bundle install
  shell: >
      source /etc/profile.d/chruby.sh
      && chruby 2.0.0-p353
      && exec bundle install --gemfile {{ release_dir }}/Gemfile --path {{ vecnet_deploy_root }}/shared/bundle --deployment --without development test
      chdir={{ release_dir }}
  sudo_user: app

- name: write_build_identifier
  shell: date '+%Y%m%d %H:%M:%S' > {{ release_dir }}/config/bundle-identifier.txt
    creates={{ release_dir }}/config/bundle-identifier.txt

- name: deploy migrate
  shell: >
      source /etc/profile.d/chruby.sh
      && chruby 2.0.0-p353
      && exec bundle exec rake RAILS_ENV={{ rails_env }} db:migrate
      chdir={{ release_dir }}
  sudo_user: app

- name: deploy precompile
  shell: >
      source /etc/profile.d/chruby.sh
      && chruby 2.0.0-p353
      && exec bundle exec rake RAILS_ENV={{ rails_env }} RAILS_GROUPS=assets assets:precompile
      chdir={{ release_dir }}
  sudo_user: app

- name: vecnet:write_env_vars
  template: >
    src=env-vars.j2
    dest={{ release_dir }}/env-vars
    owner=app
    group=app
    mode=644

- name: make discovery user
  shell: >
      source /etc/profile.d/chruby.sh
      && chruby 2.0.0-p353
      && exec bundle exec rake RAILS_ENV={{ rails_env }} UID=d_harvest APIKEY={{ d_harvest_api_key }} GROUP_LIST=dl_librarian vecnet:set_api_key
      chdir={{ release_dir }}
  sudo_user: app

- name: only keep last 6 deploys
  shell: >
      ls -1dt {{ vecnet_deploy_root }}/releases/* | tail -n +6 |  xargs rm -rf
      chdir={{ vecnet_deploy_root }}/releases


